apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-tailor
  namespace: kube-tailor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-tailor
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-tailor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-tailor
subjects:
  - kind: ServiceAccount
    name: kube-tailor
    namespace: kube-tailor
